name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *"   # Every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: nikhilsenju
          theme: tokyonight
          output: assets/trophies.svg

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update trophies"
